language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: false
  sequence_diagrams: false
  collapse_walkthrough: false
  poem: false
  auto_review:
    enabled: true
